# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: screen.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cscreen.proto\x12\x06screen\"\xb3\x01\n\x07Payload\x12\x16\n\x0e\x63ontrast_ratio\x18\x01 \x01(\t\x12\x14\n\x0cviewing_tech\x18\x02 \x01(\t\x12\x13\n\x0b\x63olor_depth\x18\x03 \x01(\t\x12\x12\n\ntouch_type\x18\x04 \x01(\t\x12\x0c\n\x04ntsc\x18\x05 \x01(\x05\x12\x13\n\x0btemperature\x18\x06 \x01(\x05\x12\x1b\n\x13\x62\x61\x63klight_longevity\x18\x07 \x01(\x05\x12\x11\n\tluminance\x18\x08 \x01(\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'screen_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PAYLOAD._serialized_start=25
  _PAYLOAD._serialized_end=204
# @@protoc_insertion_point(module_scope)
