# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: screen.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='screen.proto',
  package='screen',
  serialized_pb=_b('\n\x0cscreen.proto\x12\x06screen\"\xb3\x01\n\x07Payload\x12\x16\n\x0e\x63ontrast_ratio\x18\x01 \x01(\t\x12\x14\n\x0cviewing_tech\x18\x02 \x01(\t\x12\x13\n\x0b\x63olor_depth\x18\x03 \x01(\t\x12\x12\n\ntouch_type\x18\x04 \x01(\t\x12\x0c\n\x04ntsc\x18\x05 \x01(\x05\x12\x13\n\x0btemperature\x18\x06 \x01(\x05\x12\x1b\n\x13\x62\x61\x63klight_longevity\x18\x07 \x01(\x05\x12\x11\n\tluminance\x18\x08 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='screen.Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contrast_ratio', full_name='screen.Payload.contrast_ratio', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='viewing_tech', full_name='screen.Payload.viewing_tech', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='color_depth', full_name='screen.Payload.color_depth', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='touch_type', full_name='screen.Payload.touch_type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ntsc', full_name='screen.Payload.ntsc', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='screen.Payload.temperature', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='backlight_longevity', full_name='screen.Payload.backlight_longevity', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='luminance', full_name='screen.Payload.luminance', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=204,
)

DESCRIPTOR.message_types_by_name['Payload'] = _PAYLOAD

Payload = _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), dict(
  DESCRIPTOR = _PAYLOAD,
  __module__ = 'screen_pb2'
  # @@protoc_insertion_point(class_scope:screen.Payload)
  ))
_sym_db.RegisterMessage(Payload)


# @@protoc_insertion_point(module_scope)
